"""Assemble a human-readable PR description from the pipeline result."""

from __future__ import annotations

from app.schemas.pipeline import GenerationRequest, PipelineResult


def _test_run_line(result: PipelineResult) -> str:
    """Report the *executed* test outcome, falling back to the agent's claim."""
    ex = result.test_execution
    if ex and ex.get("ran"):
        verdict = "PASS" if ex.get("passed") else "FAIL"
        return f"[{verdict}] Executed in sandbox ({ex.get('backend')}): {ex.get('summary')}."
    return f"Validated: {'yes' if result.tests.validated else 'pending'} (not executed)."


def build_pr_body(request: GenerationRequest, result: PipelineResult) -> str:
    a = result.architecture
    sec = result.security
    opt = result.optimization
    tests = result.tests

    sec_section = (
        "No high/critical findings."
        if sec.passed
        else "\n".join(
            f"- **{f.severity.upper()}** — {f.issue} ({f.location}) → {f.fix}"
            for f in sec.findings
        )
    )
    opt_section = (
        "\n".join(f"- **{s.area}** — {s.improvement} _(impact: {s.estimated_impact})_" for s in opt.suggestions)
        or "_No suggestions._"
    )

    return f"""## Generated by the Multi-Agent Code Generator

**Request:** {request.issue_title}

### Architecture
- **Stack:** {', '.join(a.tech_stack) or 'n/a'}
- **Endpoints:** {len(a.api_endpoints)} · **Components:** {len(a.components)}

{a.rationale}

### Tests
{len(tests.files)} test file(s). {_test_run_line(result)}
{tests.coverage_notes}

### Security
{sec_section}

### Optimization
{opt_section}

---
_Produced by five coordinating agents (architect, implementation, test, security, optimization). Improves from accept/reject feedback._
"""
